### ISSUE TITLE
Crashes with node-red-contrib-freeboard installed

### ISSUE THREAD

**Issue by microspace** [monteslu/node-red-contrib-gpio#12]
Node-red crashed when https://github.com/urbiworx/node-red-contrib-freeboard is installed.

Node-RED version: v0.13.1
Node.js  version: v0.10.38

```
5 Apr 12:18:08 - [red] Uncaught Exception:

5 Apr 12:18:08 - TypeError: Object function (entry) {
  return this.indexOf(entry) !== -1;
} has no method 'end'
    at interval (/home/root/node-red/node_modules/node-red-contrib-freeboard/freeboard.js:71:12)
    at wrapper [as _onTimeout] (timers.js:261:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

Please can you point me to the problem?

**Comment by monteslu** [comment]
This looks like its just a problem with the freeboard plugin.

Did you try uninstalling node-red-contrib-freeboard and seeing if node-red-contrib-gpio still works?

**Comment by microspace** [comment]
Yes, uninstalling node-red-contrib-freeboard solves the problem. Cant you please give a glance at error part of code? Maybe there is something unisual? https://github.com/urbiworx/node-red-contrib-freeboard/blob/master/freeboard.js#L71

**Comment by gotititu** [comment]
I installed node.js 4.4.2 and the error is different
`9 Apr 16:06:37 - TypeError: resp[i].end is not a function
    at interval [as _repeat] (/usr/lib/node_modules/node-red-contrib-freeboard/freeboard.js:71:12)
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
`
The workaround via [node-red-node-dweetio ](http://flows.nodered.org/node/node-red-node-dweetio) and then using freeboard to connect to dweet datasource
