### ISSUE TITLE
about closing an serial port

### ISSUE THREAD

**Issue by sidddharth7890** [monteslu/node-red-contrib-gpio#30]
hello,
i am using johnny-five with node-red and the question is how to close the serial port which is already open?
the next problem i faced is that when i re-deploy the flow in node-red, it throws an error.

currently i am using 0.18.2 version of node-red
and node.js version 8.9.4 and operationg system that i used is windows 10

**Comment by monteslu** [comment]
just pushed up a new version (0.11.0) which has newer versions of johnny-five firmata and serialport.  Could you give that a shot?

**Comment by sidddharth7890** [comment]
ok I'll try it ....
thanks for your response...

**Comment by sidddharth7890** [comment]
which software version you supposed to me for update?

**Comment by monteslu** [comment]
try the latest contrib-gpio 0.14.0 and use that with the latest node-red running on node 6 or 8

**Comment by sidddharth7890** [comment]
first of all i wanted to thank you for taking interest in my issue, i tried it but same problem happens....after re deploying the flow it will throw an error "port is not open"

**Comment by sidddharth7890** [comment]
Welcome to Node-RED
===================

22 Feb 00:00:45 - [info] Node-RED version: v0.18.2
22 Feb 00:00:45 - [info] Node.js  version: v8.9.4
22 Feb 00:00:45 - [info] Windows_NT 10.0.16299 x64 LE
22 Feb 00:00:45 - [info] Loading palette nodes
22 Feb 00:00:47 - [info] Dashboard version 2.7.0 started at /ui
22 Feb 00:00:47 - [warn] ------------------------------------------------------
22 Feb 00:00:47 - [warn] [node-red/rpi-gpio] Info : Ignoring Raspberry Pi specific node
22 Feb 00:00:47 - [warn] [node-red/tail] Not currently supported on Windows.
22 Feb 00:00:47 - [warn] ------------------------------------------------------
22 Feb 00:00:47 - [info] Settings file  : \Users\om\.node-red\settings.js
22 Feb 00:00:47 - [info] User directory : \Users\om\.node-red
22 Feb 00:00:47 - [warn] Projects disabled : set editorTheme.projects.enabled=true to enable
22 Feb 00:00:47 - [info] Flows file     : \Users\om\.node-red\flows_DESKTOP-L5ID322.json
22 Feb 00:00:47 - [info] Server now running at http://127.0.0.1:1880/
22 Feb 00:00:47 - [info] Starting flows
1519237847996 Connected COM6
22 Feb 00:00:47 - [info] Started flows
1519237850995 Repl Initialized
>> 22 Feb 00:01:08 - [info] Stopping flows
board closed
22 Feb 00:01:08 - [info] Stopped flows
22 Feb 00:01:08 - [info] Starting flows
1519237868651 Connected COM6
22 Feb 00:01:08 - [info] Started flows
1519237868652 Error Opening COM6: Access denied
22 Feb 00:01:08 - [red] Uncaught Exception:
22 Feb 00:01:08 - Error: Unhandled "error" event. ([object Object])
    at Board.emit (events.js:186:19)
    at Board.log (C:\Users\om\Desktop\custom nodes\test\node_modules\johnny-five\lib\board.js:625:8)
    at Board.(anonymous function) [as error] (C:\Users\om\Desktop\custom nodes\test\node_modules\johnny-five\lib\board.js:636:14)
    at Board.finalizeAndBroadcast (C:\Users\om\Desktop\custom nodes\test\node_modules\johnny-five\lib\board.js:364:12)
    at Board.<anonymous> (C:\Users\om\Desktop\custom nodes\test\node_modules\johnny-five\lib\board.js:142:18)
    at Board.<anonymous> (C:\Users\om\Desktop\custom nodes\test\node_modules\johnny-five\node_modules\firmata\lib\firmata.js:544:7)
    at emitOne (events.js:116:13)
    at SerialPort.emit (events.js:211:7)
    at SerialPort.<anonymous> (C:\Users\om\Desktop\custom nodes\test\node_modules\johnny-five\node_modules\firmata\node_modules\serialport\lib\serialport.js:103:14)
    at SerialPort._error (C:\Users\om\Desktop\custom nodes\test\node_modules\johnny-five\node_modules\firmata\node_modules\serialport\lib\serialport.js:186:5)

**Comment by monteslu** [comment]
This needs to be refactored to wait for a node-red redeploy until the port is closed:  https://github.com/monteslu/node-red-contrib-gpio/blob/master/lib/nodebotNode.js#L38-L100

**Comment by PizzaProgram** [comment]
Is it possible to place a "Manual Close" inject + J5 script button on the flow?
At least we could CLICK on it, and click Deploy after a few sec. later.
_It's a real pain of testing things, if someone has to climb up to the addict to unplug/re-plug each time after changed something._
![kép](https://user-images.githubusercontent.com/26026089/100686630-01438f00-337f-11eb-956e-ad1dca00fd12.png)

I've tried it, but I'm just a beginner, so it's not working this way:
`var io = new IOPlugin();
	io.ClosePort(board.port);`
Error: "ReferenceError: IOPlugin is not defined (line 1, col 10)"

I'm not even sure about this:
- What is the recommended way to close a port? (1. Stop => 2. Flush => 3. Close? or simply Close is enough and safer?)
Opened a ticket, [here...](https://github.com/rwaldron/io-plugins/issues/24) but no answer yet.
